# Generated by Django 4.2.3 on 2023-08-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='region_id',
            new_name='region',
        ),
    ]
