# Generated by Django 4.2.3 on 2023-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0003_rename_profile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=500)),
                ('cache_expiry', models.IntegerField(default=300)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
