# Generated by Django 4.2.3 on 2023-08-18 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0005_proxycache_created_userprofile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxycache',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
