# Generated by Django 4.2.7 on 2023-12-11 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0007_bomsynclist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('any_text', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(max_length=500)),
                ('bounding_box', models.TextField(blank=True, help_text="Maps to pycsw:BoundingBox. It's a WKT geometry", null=True)),
                ('crs', models.CharField(blank=True, help_text='Maps to pycsw:CRS', max_length=255, null=True)),
                ('service_type', models.CharField(blank=True, max_length=10)),
                ('service_type_version', models.CharField(blank=True, max_length=10)),
                ('legend', models.CharField(max_length=500)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
