# Generated by Django 4.2.7 on 2023-12-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0008_catalogue_cataloguetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguetag',
            name='catalogue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sss.catalogue'),
        ),
    ]
