# Generated by Django 4.2.7 on 2023-12-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0011_catalogue_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='catalogue',
            name='map_server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sss.mapserver'),
        ),
    ]
