# Generated by Django 4.2.7 on 2023-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0013_mapserver_created_mapserver_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapserver',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mapserver',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
