# Generated by Django 4.2.7 on 2023-12-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0014_mapserver_name_mapserver_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='type',
            field=models.CharField(blank=True, help_text='Map Server Type TileLayer, ImageLayer, WMSLayer etc', max_length=500, null=True),
        ),
    ]
