# Generated by Django 4.2.7 on 2023-12-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0016_alter_catalogue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('TileLayer', 'TileLayer'), ('WMSLayer', 'WMSLayer'), ('ImageLayer', 'ImageLayer')], default='', help_text='Map Server Type TileLayer, ImageLayer, WMSLayer etc', max_length=128, null=True),
        ),
    ]
