# Generated by Django 4.2.7 on 2023-12-14 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0017_alter_catalogue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueSyncCSW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=500)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('removed_from_csw', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
