# Generated by Django 4.2.7 on 2023-12-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0018_cataloguesynccsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguesynccsw',
            name='csw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
