# Generated by Django 4.2.8 on 2023-12-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0019_cataloguesynccsw_csw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='workspace',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('TileLayer', 'TileLayer'), ('TileLayer2', 'TileLayer2'), ('WMSLayer', 'WMSLayer'), ('ImageLayer', 'ImageLayer')], default='', help_text='Map Server Type TileLayer, ImageLayer, WMSLayer etc', max_length=128, null=True),
        ),
    ]
