# Generated by Django 5.0.7 on 2024-08-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0022_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
