# Generated by Django 5.0.8 on 2024-11-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0024_spatialdatacalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatacalculation',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
