# Generated by Django 5.0.8 on 2024-11-14 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0025_spatialdatacalculation_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatacalculation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spatialdatacalculation',
            name='calculation_status',
            field=models.CharField(choices=[('Imported', 'Imported'), ('Calculating', 'Calculating'), ('Processing Finalised', 'Processing Finalised'), ('Failed', 'Failed'), ('Completed', 'Completed')], default='Imported', max_length=40, verbose_name='Calculation Status'),
        ),
        migrations.AlterField(
            model_name='spatialdatacalculation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
