# Generated by Django 5.0.8 on 2024-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0026_spatialdatacalculation_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatacalculation',
            name='tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
