# Generated by Django 5.0.8 on 2024-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0027_spatialdatacalculation_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatacalculation',
            name='spatial_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
