# Generated by Django 5.0.8 on 2025-01-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0028_spatialdatacalculation_spatial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialdatacalculation',
            name='calculation_status',
            field=models.CharField(choices=[('Imported', 'Imported'), ('Calculating', 'Calculating'), ('Processing Finalised', 'Processing Finalised'), ('Calculation Error', 'Calculation Error'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Imported', max_length=40, verbose_name='Calculation Status'),
        ),
    ]
