# Generated by Django 5.0.8 on 2025-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0029_alter_spatialdatacalculation_calculation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialdatacalculation',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
