# Generated by Django 5.0.8 on 2025-01-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0030_spatialdatacalculation_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialdatacalculation',
            name='logs',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
