# Generated by Django 5.2.3 on 2025-07-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0032_crssettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crssettings',
            options={'verbose_name': 'CRS Setting', 'verbose_name_plural': 'CRS Setting'},
        ),
        migrations.AddField(
            model_name='proxycache',
            name='browser_expiry',
            field=models.IntegerField(default=300),
        ),
    ]
