# Generated by Django 5.2.3 on 2025-07-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0033_alter_crssettings_options_proxycache_browser_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxycache',
            name='browser_expiry',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
