# Generated by Django 5.2.6 on 2025-10-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0034_alter_proxycache_browser_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommandStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Management Command Status',
                'verbose_name_plural': 'Management Command Status',
                'ordering': ['-completion_time'],
            },
        ),
    ]
