# Generated by Django 5.2.7 on 2025-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0035_managementcommandstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='service_type',
            field=models.CharField(blank=True, default='WMS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='service_type_version',
            field=models.CharField(blank=True, default='1.1.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('TileLayer', 'TileLayer'), ('TileLayer2', 'TileLayer2'), ('TileWMSLayer', 'TileWMSLayer'), ('WMSLayer', 'WMSLayer'), ('ImageLayer', 'ImageLayer'), ('WFSLayer', 'WFSLayer')], default='', help_text='Map Server Type TileLayer, ImageLayer, WMSLayer etc', max_length=128, null=True),
        ),
    ]
