# Generated by Django 5.2.7 on 2025-11-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0036_alter_catalogue_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='service_type_version',
            field=models.CharField(blank=True, default='1.1.1', max_length=10, null=True),
        ),
    ]
